- hosts: all
  roles:
    - base
    - geerlingguy.ntp
    - hifis.toolkit.unattended_upgrades

- hosts: hyp-par.trickey.uk
  roles:
    - incus

- hosts: dck-par.trickey.uk
  roles:
    - geerlingguy.docker
    - docker_cleanup
    - authentik
    - netbox
    - prometheus
    - tandoor
    - traefik
