- name: Install compose-switch
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: "0755"
  when: ansible_os_family == 'Debian'

- name: Install python3-requests for ansible.community.docker
  package:
    name:
      - python3-requests
    state: present

- name: Create docker group
  group:
    name: "{{ docker_user.name }}"
    state: present
    gid: "{{ docker_user.id }}"

- name: Create docker user
  user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"
    group: "{{ docker_user.name }}"
    create_home: false

- name: Add user to docker user group
  user:
    name: "{{ me.user }}"
    groups: "{{ docker_user.name }}"
    append: true

- name: Add user to docker group
  user:
    name: "{{ me.user }}"
    groups: docker
    append: true

- name: Clean up docker containers
  cron:
    name: clean up docker containers
    hour: 1
    minute: 0
    job: docker system prune -af --volumes
    cron_file: docker_cleanup
    user: root
