- name: Include vault
  include_vars: vault.yml
  tags: vikunja

- name: Create install directory
  file:
    path: /opt/vikunja
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  tags: vikunja

- name: Install config file
  template:
    src: files/config.yml
    dest: /opt/vikunja/config.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart vikunja
  tags: vikunja

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/vikunja/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart vikunja
  tags: vikunja
