- name: Create install directory
  file:
    path: /opt/prometheus
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  tags: prometheus

- name: Create config directory
  file:
    path: /opt/prometheus/prometheus
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  tags: prometheus

- name: Install prometheus config
  template:
    src: files/prometheus.yml
    dest: /opt/prometheus/prometheus/prometheus.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart prometheus
  tags: prometheus

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/prometheus/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart prometheus
  tags: prometheus
