name: Lint

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pip install poetry
      - name: Use in-project virtualenv
        run: poetry config virtualenvs.in-project true
      - uses: actions/cache@v2
        with:
          path: .venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: make lint
